### ISSUE TITLE
Missing rebar3_hex repository required in teacup_nats

### ISSUE THREAD

**Issue by warehog** [yuce/teacup_nats#11]
Hello! 
   There is missing repository, and plugin defined in teacup_nats rebar.config file cannot be downloaded

`===> Verifying dependencies...
===> Fetching rebar3_hex ({git,"https://github.com/yuce/rebar3_hex.git",
                                      {branch,"add-notice-file-to_defaults"}})
===> Plugin {rebar3_hex,{git,"https://github.com/yuce/rebar3_hex.git",
                                    {branch,"add-notice-file-to_defaults"}}} not available. It will not be used.`

**Comment by yuce** [comment]
Thanks!

Removed that plugin and updated the package to 0.4.1: https://hex.pm/packages/teacup_nats/0.4.1 Can you give it a try ?

**Comment by warehog** [comment]
Yes, it works now, thanks for update :)
